variable "access_key" {}
variable "secret_key" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "region1" {}
variable "zone1" {}
variable "region2" {}
variable "zone2" {}
variable "project_name" {}
